# Generated by Django 5.2.4 on 2025-08-04 17:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tarefa",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "descricao",
                    models.CharField(max_length=200, verbose_name="Descrição"),
                ),
                ("data_inicio", models.DateField(verbose_name="Data de Início")),
                ("data_termino", models.DateField(verbose_name="Data de Término")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("A fazer", "A fazer"),
                            ("Em andamento", "Em andamento"),
                            ("Concluída", "Concluída"),
                        ],
                        default="A fazer",
                        max_length=20,
                    ),
                ),
            ],
        ),
    ]
